changeLogFile=Configuration Files/changelog.json
url=jdbc:sqlserver://gescomph.database.windows.net:1433;database=gescomph_develop;encrypt=true;trustServerCertificate=false
username=gescomph
password=Admin123.
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
logLevel=info
contexts=develop
